server:
  port: 8088
spring:
  application:
    name: Intro project
  datasource:
    url: jdbc:postgresql://localhost:5432/lundegaard
    username: lundegaard
    password: lundegaard
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQL95Dialect
      hibernate.jdbc.lob.non_contextual_creation: true
  flyway:
    baseline-on-migrate: true
    locations: classpath:/db/migration,classpath:/db/data
    clean-on-validation-error: true
    enabled: true